- name: Install virtualenv packages
  apt:
    name: [ python3.8-venv ]
    state: latest

- name: Creates directory
  file:
    path: "{{ autoscaling_home }}"
    state: directory
  become_user: "{{ autoscaling_user }}"

- name: Check if {{ autoscaling_env }}  already installed
  stat:
    path: "{{ autoscaling_home }}/{{ autoscaling_env }}"
  register: virtualenv_installed

- name: Create the initial virtualenv
  command:
    cmd: python3.8 -m venv "{{ autoscaling_home }}/{{ autoscaling_env }}"
    creates: "{{ autoscaling_home }}/{{ autoscaling_env }}"
  become_user: "{{ autoscaling_user }}"
  when: virtualenv_installed.stat.exists == False

- name: Download requirements
  ansible.builtin.shell: wget "https://raw.githubusercontent.com/deNBI/autoscaling-cluster/{{autoscaling_version}}/requirements.txt" -O {{ autoscaling_home }}/requirements.txt
  args:
    executable: /bin/bash
    creates: "{{ autoscaling_home }}/requirements.txt"
  become_user: "{{ autoscaling_user }}"

- name: Install pip packages
  pip:
    name: "{{ autoscaling_home }}/requirements.txt"
    virtualenv: "{ { autoscaling_home } }/{{ autoscaling_env }}"
  become_user: "{{ autoscaling_user }}"

- name: Check if {{ autoscaling_env }} installed
  stat:
    path: "{{ autoscaling_home }}/{{ autoscaling_env }}"
  register: virtualenv_installed
  
