
- name: Create autoscaling systemd service file
  template:
    src: autoscaling/autoscaling.service
    dest: /etc/systemd/system/autoscaling.service

- name: Download autoscaling.py
  ansible.builtin.uri:
    url: "https://raw.githubusercontent.com/deNBI/autoscaling-cluster/{{ autoscaling_version }}/autoscaling.py"
    dest: "{{ autoscaling_home }}/autoscaling.py"
    force: yes
  become_user: "{{ autoscaling_user }}"

- name: Download autoscaling config
  ansible.builtin.uri:
    url: "https://raw.githubusercontent.com/deNBI/autoscaling-cluster/{{ autoscaling_version }}/autoscaling_config.yaml"
    dest: "{{ autoscaling_home }}/autoscaling_config.yaml"
    force: yes
  become_user: "{{ autoscaling_user }}"

- name: Add alias for autoscaling
  ansible.builtin.lineinfile:
    path=/home/{{autoscaling_user}}/.bashrc
    line="alias autoscaling='{{ autoscaling_home }}/{{ autoscaling_env }}/bin/python {{ autoscaling_home }}/autoscaling.py'"
    regexp='^alias autoscaling='
    state=present
    insertafter=EOF
  become_user: "{{ autoscaling_user }}"
